language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE SurgeX_DB;'
  - sudo mysql -e 'USE SurgeX_DB;'
  - sudo mysql -e 'CREATE TABLE user(
                   username char(50) NULL,
                   passwd char(50) NULL
                   )ENGINE=InnoDB;'
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - ./build.sh
