language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE SurgeX_DB;'
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - ./build.sh
