language: cpp
sudo: required
dist: bionic
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
services:
  - mysql
addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client
before_script:
  - sudo mysql -e 'CREATE DATABASE SurgeX_DB;
                   USE SurgeX_DB;
                   CREATE TABLE user(
                                    username char(50) NULL,
                                    passwd char(50) NULL
                                    )ENGINE=InnoDB;'
  - mysql_config
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - ./build.sh
