language: cpp
sudo: required
dist: bionic
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE SurgeX_DB;
                   USE SurgeX_DB;
                   CREATE TABLE user(
                                    username char(50) NULL,
                                    passwd char(50) NULL
                                    )ENGINE=InnoDB;'
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - ./build.sh
